(function(){
 'use strict';
 const {url,escape:H,read,write}=LMBC,C=PortalCore,app=document.getElementById('portal-content'),page=document.body.dataset.portal;
 const params=new URLSearchParams(location.search);let state=null,index=[],tournamentsError=false,category=params.get('categoria')||read('lmbc_category'),season=params.get('temporada')||'',loadVersion=0;
 const opts=(xs,value)=>xs.map(x=>`<option value="${H(x.id)}" ${x.id===value?'selected':''}>${H(x.nombre??x.name)}</option>`).join('');
 const optionInput=(label,id,xs,value)=>`<label>${label}<select id="${id}">${opts(xs,value)}</select></label>`;
 async function json(p){const r=await fetch(url(p),{cache:'no-cache'});if(!r.ok)throw Error('No se pudo cargar la información.');return r.json();}
 function game(g){const side=(id,score)=>{const t=state.equiposPorId[id];return `<div class="game-side"><img src="${url(t?.logo||'img/equipos/placeholder.svg')}" alt=""><span>${H(t?.nombre||'Por definir')}</span><b>${g.estatus==='jugado'?H(score):''}</b></div>`;};const cat=state.categorias.find(c=>c.id===g.categoria_id)?.nombre??'';return `<a class="game-mini" href="${url('calendario/?juego='+encodeURIComponent(g.id)+'&categoria='+encodeURIComponent(g.categoria_id)+'&temporada='+encodeURIComponent(g.temporada))}"><div class="game-meta"><span>${H(cat)}</span><span class="game-state">${g.fase==='amistoso'?'Amistoso':g.estatus==='jugado'?'Finalizado':'Liga'}</span></div>${side(g.local,g.marcador_local)}${side(g.visita,g.marcador_visita)}<small>${H(formatearFecha(g.fecha).texto)} · ${H(g.hora)} · ${H(state.sedesPorId[g.sede_id]?.nombre||'Cancha por definir')}</small></a>`;}
 function filters(){return `<div class="portal-filters">${optionInput('Categoría y rama','portal-category',[{id:'',nombre:'Todas las categorías'},...state.categorias],category)}${optionInput('Temporada de liga','portal-season',state.temporadas,season)}</div>`;}
 function bindFilters(){document.getElementById('portal-category')?.addEventListener('change',e=>{category=e.target.value;write('lmbc_category',category);renderHome();});document.getElementById('portal-season')?.addEventListener('change',async e=>{season=e.target.value;await loadHome();});}
 function renderHome(){
  const filtered=C.filterGames(state.juegos,{category,season}),next=C.upcoming(filtered,fechaLocalISO()),last=C.recent(filtered),favorite=read('lmbc_favorite'),team=state.equiposPorId[favorite],teamCat=state.equipos.find(e=>e.id===favorite&&(!category||e.categoria_id===category))?.categoria_id||state.equipos.find(e=>e.id===favorite)?.categoria_id||'',mine=C.filterGames(filtered,{team:favorite}),myNext=team?C.upcoming(mine,fechaLocalISO())[0]:null,myLast=team?C.recent(mine)[0]:null;const leaders=C.leaders(filtered,state.jugadoresPorId),points=[...leaders].sort((a,b)=>b.points-a.points)[0],threes=[...leaders].sort((a,b)=>b.threes-a.threes)[0];
  const tournamentCards=index.filter(t=>['publicado','finalizado'].includes(t.status)).sort((a,b)=>(b.start||'').localeCompare(a.start||'')).slice(0,3);
  app.innerHTML=`${filters()}<div class="portal-top"><section class="spotlight"><span class="eyebrow">Nos vemos en la cancha</span><h2>${next.length?'La próxima jornada':'Toda la actividad de la liga'}</h2>${next[0]?game(next[0]):'<p>No hay partidos próximos en esta selección.</p>'}<div class="favorite-actions"><a class="secondary-link" href="${url('calendario/?categoria='+encodeURIComponent(category))}">Ver todos los partidos →</a></div></section><section class="portal-card"><span class="eyebrow">Tu lugar en la tribuna</span><h2 style="margin-top:8px">${team?H(team.nombre):'Sigue a tu equipo'}</h2>${team?`<img class="favorite-mark" src="${url(team.logo||'img/equipos/placeholder.svg')}" alt="Logo de ${H(team.nombre)}"><p>${myNext?'Próximo partido: '+H(formatearFecha(myNext.fecha).texto)+' · '+H(myNext.hora):myLast?'Último resultado: '+H(myLast.marcador_local)+' – '+H(myLast.marcador_visita):'Sin partidos en la categoría y temporada seleccionadas.'}</p><div class="favorite-actions"><a class="primary-link" href="${url('equipos/?equipo='+encodeURIComponent(favorite)+'&categoria='+encodeURIComponent(teamCat)+'&temporada='+encodeURIComponent(season))}">Ver equipo</a><a class="secondary-link" href="${url('calendario/?equipo='+encodeURIComponent(favorite))}">Sus partidos</a><button class="icon-button" data-favorite-open>Cambiar equipo</button></div>`:'<p>Elige tu equipo para consultar sus partidos, resultados y roster. Lo recordaremos en este navegador.</p><button class="primary-link" data-favorite-open>☆ Elegir mi equipo</button><p class="leader-label">No necesitas crear una cuenta.</p>'}</section></div>
  <section class="portal-section"><div class="section-heading"><h2>Próximos partidos</h2><a href="${url('calendario/?estado=programado')}">Calendario completo →</a></div><div class="card-grid">${next.slice(0,6).map(game).join('')||'<div class="portal-empty">No hay próximos partidos en esta selección.</div>'}</div></section>
  <section class="portal-section"><div class="section-heading"><h2>Últimos resultados</h2><a href="${url('calendario/?estado=jugado')}">Todos los resultados →</a></div><div class="card-grid">${last.slice(0,3).map(game).join('')||'<div class="portal-empty">Aún no hay resultados en esta selección.</div>'}</div></section>
  <section class="portal-section"><div class="section-heading"><h2>Destacados por categoría</h2><a href="${url('lideres/?categoria='+encodeURIComponent(category)+'&temporada='+encodeURIComponent(season))}">Ver líderes →</a></div><div class="card-grid">${state.categorias.filter(c=>!category||c.id===category).map(c=>{const rows=C.leaders(C.filterGames(filtered,{category:c.id}),state.jugadoresPorId),p=[...rows].sort((a,b)=>b.points-a.points)[0],t=[...rows].sort((a,b)=>b.threes-a.threes)[0];return `<article class="portal-card"><span class="eyebrow">${H(c.nombre)}</span><div class="stat-number">${p?p.points:'—'} <span class="leader-label">puntos</span></div>${p?'<a href="'+url('jugador/?id='+encodeURIComponent(p.id))+'"><strong>'+H(p.name)+'</strong></a>':'<strong>Sin estadísticas todavía</strong>'}<p>Triples: ${t?H(t.name)+' · '+t.threes:'Sin registros'}</p><p class="leader-label">Acumulado oficial · ${H(season)}</p><a class="category-link" href="${url('standing/?categoria='+encodeURIComponent(c.id)+'&temporada='+encodeURIComponent(season))}">Ver posiciones <span>↗</span></a></article>`;}).join('')}</div></section>
  <section class="portal-section"><div class="section-heading"><h2>Torneos independientes</h2><a href="${url('torneos/')}">Explorar torneos →</a></div>${tournamentCards.length?`<div class="card-grid">${tournamentCards.map(t=>`<a class="portal-card action-card" href="${url('torneos/?id='+encodeURIComponent(t.id))}"><span class="eyebrow">${H(t.status)}</span><h2 style="margin:12px 0">${H(t.name)}</h2><p>${H(t.start||'Fecha por confirmar')} · ${t.divisions.length} categorías / ramas</p><span class="arrow">Ver torneo →</span></a>`).join('')}</div>`:`<div class="portal-empty">${tournamentsError?'No se pudo cargar el catálogo de torneos. Abre Explorar torneos para volver a intentar.':'Los próximos torneos aparecerán aquí cuando se publiquen. Cada uno tendrá sus equipos, grupos y estadísticas.'}</div>`}</section>`;
  bindFilters();renderPatrocinadores(state.patrocinadores);
 }
 async function loadHome(){const version=++loadVersion;app.innerHTML='<div class="loading-state" role="status"><span class="loading-dot"></span>Cargando partidos y resultados…</div>';try{const nextState=await cargarDatos({temporada:season||'activa'});if(version!==loadVersion)return;state=nextState;season=season||state.temporadas.find(t=>String(t.activa)==='true')?.id||[...state.temporadas].sort((a,b)=>b.id.localeCompare(a.id))[0]?.id||'';if(!state.categorias.some(c=>c.id===category))category='';renderHome();}catch(e){app.innerHTML='<div class="portal-empty" role="alert">No se pudo cargar la portada. <button onclick="location.reload()">Reintentar</button></div>';}}
 async function adminPage(){const [cats,temps,catalog]=await Promise.all([json('data/categorias.json'),json('data/temporadas.json'),json('data/torneos/index.json')]);app.innerHTML=`<div class="admin-context">${optionInput('¿Qué vas a administrar?','admin-environment',[{id:'liga',nombre:'Liga'},{id:'amistoso',nombre:'Amistosos'},{id:'torneo',nombre:'Torneos relámpago'}],params.get('modo')||'liga')}<div id="admin-league">${optionInput('Categoría y rama','admin-category',cats,category||cats[0]?.id)}</div><div id="admin-season-wrap">${optionInput('Temporada','admin-season',temps.temporadas,temps.temporadas.find(t=>String(t.activa)==='true')?.id)}</div><div id="admin-tournament-wrap" hidden>${optionInput('Torneo','admin-tournament',[{id:'',nombre:'Elegir / crear un torneo'},...catalog.torneos.map(t=>({id:t.id,nombre:t.name}))],'')}</div></div><div class="context-label" id="admin-context-label"></div><div class="card-grid" id="admin-actions"></div><section class="portal-section"><h2>Herramientas de la liga</h2><p class="muted">Registro oficial, temporadas, sedes y noticias.</p><div class="site-links"><a href="${url('admin/#/collections/equipos/entries/equipos')}">Equipos oficiales y logos</a><a href="${url('admin/#/collections/jugadores/entries/jugadores')}">Registro oficial</a><a href="${url('admin/')}">Panel de contenido</a><a href="${url('torneos/?administrar=1')}">Todos los torneos</a></div></section><p class="results-note">Las herramientas de captura comparten tu token en este navegador. El panel de contenido conserva su acceso habitual.</p>`;
  const render=()=>{const mode=document.getElementById('admin-environment').value,cat=document.getElementById('admin-category').value,temp=document.getElementById('admin-season').value,tid=document.getElementById('admin-tournament').value,tor=mode==='torneo',q=new URLSearchParams({modo:mode,categoria:cat,temporada:temp});document.getElementById('admin-league').hidden=tor;document.getElementById('admin-season-wrap').hidden=tor;document.getElementById('admin-tournament-wrap').hidden=!tor;document.getElementById('admin-context-label').textContent=tor?'Entorno: '+(catalog.torneos.find(t=>t.id===tid)?.name||'Torneos relámpago')+' · Categoría y rama se eligen dentro del torneo.':'Entorno: '+(mode==='liga'?'Liga':'Amistosos')+' · '+cats.find(c=>c.id===cat)?.nombre+' · '+temp;const target=view=>'torneos/?administrar=1'+(tid?'&id='+encodeURIComponent(tid):'')+'&vista='+view;const rows=tor?[['▦','Programar y editar juegos','Genera el rol y modifica fechas y canchas.',target('rol')],['✎','Capturar resultados','Marcadores, puntos, triples y faltas.',target('captura')],['♟','Equipos, logos y rosters','Inscripciones independientes por categoría.',target('equipos')],['≋','Grupos y posiciones','Distribución, standing y clasificados.',target('grupos')],['↗','Llaves','Eliminación a un partido hasta el campeón.',target('llaves')],['⚙','Configurar torneo','Nombre, categorías, ramas, canchas y papelera.',target('config')]]:[['▦','Programar, editar o eliminar','Organiza el rol y reprograma encuentros.','agregar-juego/?'+q],['✎','Capturar resultados','Abre un juego y registra su hoja de estadísticas.','captura/?'+q],['♟','Jugadores y rosters','Altas e inscripciones en el entorno seleccionado.','nuevo-jugador/?'+q],['★','Equipos y logos',mode==='amistoso'?'Crea equipos invitados o cambia su logo desde la agenda.':'Edita los equipos y logos del registro oficial.',mode==='amistoso'?'agregar-juego/?'+q:'admin/#/collections/equipos/entries/equipos'],['◷','Consultar partidos','Revisa fechas, resultados y hojas de estadísticas.','calendario/?tipo='+mode+'&categoria='+encodeURIComponent(cat)],['↗','Ver estadísticas',mode==='amistoso'?'Consulta la hoja individual de cada amistoso.':'Tabla de posiciones y líderes de la categoría.',mode==='amistoso'?'calendario/?tipo=amistoso':'standing/?categoria='+encodeURIComponent(cat)+'&temporada='+encodeURIComponent(temp)]];document.getElementById('admin-actions').innerHTML=rows.map(([icon,title,desc,p])=>`<a class="portal-card action-card" href="${url(p)}"><span class="card-icon" aria-hidden="true">${icon}</span><h2>${title}</h2><p>${desc}</p><span class="arrow">Abrir →</span></a>`).join('');};app.querySelectorAll('select').forEach(e=>e.onchange=render);render();
 }
 async function venuesPage(){const [venues,sponsors]=await Promise.all([json('data/sedes.json'),json('data/patrocinadores.json')]);app.innerHTML='<div class="card-grid">'+(venues.sedes??venues).map(v=>`<article class="portal-card"><span class="eyebrow">Sede de juegos</span><h2 style="margin:12px 0">${H(v.nombre)}</h2>${v.direccion?'<p>'+H(v.direccion)+'</p>':''}<a class="secondary-link" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(v.nombre+' Caborca Sonora')}">Buscar ubicación ↗</a></article>`).join('')+'</div><section class="portal-section"><h2>Quienes apoyan nuestra liga</h2><p class="muted">Gracias por hacer equipo con el básquetbol de Caborca.</p><div id="patrocinadores"></div></section>';renderPatrocinadores(sponsors.patrocinadores??sponsors);}
 if(page==='inicio'){json('data/torneos/index.json').then(x=>{index=x.torneos;if(state)renderHome();}).catch(()=>{tournamentsError=true;if(state)renderHome();});loadHome();window.addEventListener('lmbc:favorite',()=>{if(state)renderHome();});}else (page==='administrar'?adminPage():venuesPage()).catch(e=>{app.innerHTML='<div class="portal-empty" role="alert">'+H(e.message)+' <button onclick="location.reload()">Reintentar</button></div>';});
})();
