(function(){
 'use strict';
 const base=new URL('../',document.currentScript.src),url=p=>new URL(p,base).href,H=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=k=>{try{return localStorage.getItem(k)||'';}catch{return '';}},write=(k,v)=>{try{localStorage.setItem(k,v);}catch{}};
 const path=location.pathname.slice(base.pathname.length).split('/')[0]||'inicio';
 const admin=['administrar','agregar-juego','captura','nuevo-jugador'].includes(path)||(path==='torneos'&&new URLSearchParams(location.search).get('administrar')==='1');
 const groups={partidos:['calendario','playoffs'],estadisticas:['estadisticas','standing','lideres','rankings','comparar','dashboard'],equipos:['equipos','jugador'],mas:['noticias','sedes']};
 const active=k=>k==='inicio'?['inicio','index.html'].includes(path):path===k||(groups[k]||[]).includes(path);
 const link=(p,label,key,cls='')=>`<a class="${cls} ${active(key)?'active':''}" ${active(key)?'aria-current="page"':''} href="${url(p)}">${label}</a>`;
 let searchData;
 async function catalog(){if(!searchData)searchData=Promise.all(['equipos','roster','categorias'].map(async p=>{const r=await fetch(url('data/'+p+'.json'));if(!r.ok)throw Error('No se pudo cargar el directorio. Intenta nuevamente.');return r.json();})).catch(e=>{searchData=null;throw e;});return searchData;}
 async function directory(favorite=false){
  const dlg=document.getElementById('site-dialog');dlg.innerHTML=`<div class="dialog-head"><h2>${favorite?'Mi equipo':'Buscar equipos y jugadores'}</h2><button type="button" class="icon-button" data-close aria-label="Cerrar">✕</button></div><label class="search-label">${favorite?'Encuentra tu equipo de liga':'Nombre del equipo o jugador'}<input id="site-query" type="search" autocomplete="off" placeholder="Escribe un nombre…"></label><p id="search-status" role="status">Cargando directorio…</p><div id="site-results" class="search-results"></div>`;dlg.showModal();dlg.querySelector('[data-close]').onclick=()=>dlg.close();const input=dlg.querySelector('input');input.focus();
  try{const [teamData,playerData,categories]=await catalog();if(!dlg.open)return;const render=()=>{const q=input.value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const match=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q);const teams=teamData.equipos.filter(e=>match(e.nombre));const players=favorite?[]:playerData.jugadores.filter(p=>q.length>=2&&match(p.nombre));const results=teams.map(e=>({name:e.nombre,note:(e.categorias||[]).map(c=>categories.find(x=>x.id===c)?.nombre||c).join(' · '),id:e.id,cat:e.categorias?.[0],logo:e.logo,team:true})).concat(players.map(p=>({name:p.nombre,note:'Jugador · '+[...new Set((p.membresias||[]).map(m=>teamData.equipos.find(e=>e.id===m.equipo_id)?.nombre).filter(Boolean))].join(', '),id:p.id})));document.getElementById('search-status').textContent=results.length+' coincidencias'+(results.length>30?' · Refina tu búsqueda para ver más':'');document.getElementById('site-results').innerHTML=(favorite?'<button class="search-result" data-favorite="">Mostrar todos los equipos</button>':'')+results.slice(0,30).map(r=>favorite?`<button class="search-result" data-favorite="${H(r.id)}"><img src="${url(r.logo||'img/equipos/placeholder.svg')}" alt=""><span><strong>${H(r.name)}</strong><small>${H(r.note)}</small></span>${read('lmbc_favorite')===r.id?'★':''}</button>`:`<a class="search-result" href="${url(r.team?'equipos/?equipo='+encodeURIComponent(r.id)+'&categoria='+encodeURIComponent(r.cat||''):'jugador/?id='+encodeURIComponent(r.id))}"><span><strong>${H(r.name)}</strong><small>${H(r.note)}</small></span><span aria-hidden="true">↗</span></a>`).join('');};input.oninput=render;render();dlg.onclick=e=>{const b=e.target.closest('[data-favorite]');if(!b)return;write('lmbc_favorite',b.dataset.favorite);dlg.close();window.dispatchEvent(new CustomEvent('lmbc:favorite'));};}catch(e){document.getElementById('search-status').textContent=e.message;}
 }
 function init(){
  let header=document.querySelector('.site-header');if(!header){header=document.createElement('header');document.body.prepend(header);}header.className='site-header';header.innerHTML=`<a class="skip-link" href="#main-content">Saltar al contenido</a><div class="site-header__inner"><a class="brand" href="${url('')}"><img class="brand__mark" src="${url('img/equipos/logovets.png')}" alt=""><span><span class="brand__name">LMBC</span><span class="brand__sub">Básquetbol · Caborca</span></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menú ☰</button><nav id="main-nav" class="site-nav" aria-label="Navegación principal">${link('','Inicio','inicio')}${link('calendario/','Partidos','partidos')}${link('equipos/','Equipos','equipos')}${link('estadisticas/','Estadísticas','estadisticas')}${link('torneos/','Torneos','torneos')}<details class="nav-more"><summary>Más</summary><div>${link('noticias/','Noticias','mas')}${link('sedes/','Sedes y patrocinadores','mas')}${link('administrar/','Administrar','administrar')}</div></details></nav><div class="header-actions"><button class="icon-button" data-search aria-label="Buscar equipos y jugadores">⌕ <span>Buscar</span></button><button class="icon-button favorite-action" data-favorite-open>☆ Mi equipo</button></div></div>`;
  header.querySelector('.menu-toggle').onclick=e=>{const open=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',String(open));header.classList.toggle('menu-open',open);};
  const stats=[['standing/','Posiciones'],['lideres/','Líderes'],['rankings/','Rankings'],['comparar/','Comparar'],['dashboard/','Resumen']];let sectionLinks=groups.estadisticas.includes(path)?stats:groups.partidos.includes(path)?[['calendario/','Calendario y resultados'],['playoffs/','Playoffs de liga']]:admin?[['administrar/','Panel de administración'],['agregar-juego/','Programar juegos'],['captura/','Capturar resultados'],['nuevo-jugador/','Jugadores'],['torneos/?administrar=1','Administrar torneos']]:[];
  if(sectionLinks.length){const sub=document.createElement('nav');sub.className='section-nav';sub.setAttribute('aria-label',admin?'Herramientas de administración':'Secciones');sub.innerHTML=sectionLinks.map(([p,n])=>`<a href="${url(p)}" ${p.split('/')[0]===path?'aria-current="page"':''}>${n}</a>`).join('');header.after(sub);}
  const main=document.querySelector('main')||document.querySelector('.cap-wrap');if(main){main.id=main.id||'main-content';header.querySelector('.skip-link').href='#'+main.id;}
  const pinTables=()=>document.querySelectorAll('.standing-table,.tor-table').forEach(table=>{const cells=table.querySelectorAll('thead tr:first-child th');table.classList.toggle('pin-second',cells.length>1&&/^#|^pos/i.test(cells[0].textContent.trim())&&/equipo|jugador|nombre/i.test(cells[1].textContent));});pinTables();if(main){const observer=new MutationObserver(pinTables);observer.observe(main,{childList:true,subtree:true});}
  const dlg=document.createElement('dialog');dlg.id='site-dialog';dlg.className='site-dialog';document.body.append(dlg);
  document.addEventListener('click',e=>{if(e.target.closest('[data-search]'))directory();if(e.target.closest('[data-favorite-open]'))directory(true);});
  const dock=document.createElement('nav');dock.className='mobile-dock';dock.setAttribute('aria-label','Accesos rápidos');dock.innerHTML=`${link('','Inicio','inicio')}${link('calendario/','Partidos','partidos')}<button data-favorite-open>☆ Mi equipo</button>${link('torneos/','Torneos','torneos')}`;document.body.append(dock);
  const foot=document.querySelector('.site-footer');if(foot)foot.innerHTML=`<div><strong>LMBC</strong><span>La cancha nos une.</span></div><div><a href="${url('administrar/')}">Administrar</a><a href="${url('sedes/')}">Sedes y patrocinadores</a><small>© ${new Date().getFullYear()} · Básquetbol de Veteranos Caborca</small></div>`;
  const content=document.getElementById('contenido');if(content&&!content.children.length)content.innerHTML='<div class="loading-state" role="status"><span class="loading-dot"></span>Cargando información de la liga…</div>';
  const banner=document.createElement('div');banner.className='data-notice';banner.hidden=true;banner.setAttribute('role','alert');header.after(banner);window.addEventListener('lmbc:data-error',()=>{banner.hidden=false;banner.innerHTML='No se pudo cargar parte de la información. Los datos mostrados pueden estar incompletos. <button type="button">Reintentar</button>';banner.querySelector('button').onclick=()=>location.reload();});
  if(['agregar-juego','captura','nuevo-jugador'].includes(path)){const wrap=document.querySelector('.cap-wrap');if(wrap){const context=document.createElement('div');context.className='cap-context';context.setAttribute('role','status');wrap.prepend(context);const update=()=>{const mode=document.getElementById('modo-captura')||document.getElementById('sel-alcance');const category=document.getElementById(mode?.value==='amistoso'?'am-categoria':'sel-categoria')||document.getElementById('sel-cat');const season=document.getElementById(mode?.value==='amistoso'?'am-temporada':'sel-temporada');context.textContent='Estás administrando: '+(mode?.value==='amistoso'?'Amistosos independientes':'Liga')+[category,season].filter(e=>e?.value).map(e=>' · '+e.options[e.selectedIndex].text).join('');};document.addEventListener('change',update);update();}}
  const favoriteLabel=()=>{document.querySelectorAll('.favorite-action').forEach(e=>e.textContent=read('lmbc_favorite')?'★ Mi equipo':'☆ Mi equipo');};window.addEventListener('lmbc:favorite',favoriteLabel);favoriteLabel();
  // Deep links from the administration hub apply only to fields that have loaded.
  const params=new URLSearchParams(location.search);if(['agregar-juego','captura','nuevo-jugador'].includes(path)){const pending=[['categoria',['sel-categoria','sel-cat']],['temporada',['sel-temporada']]];if(path==='nuevo-jugador'&&params.get('modo')==='amistoso')pending.unshift(['modo',['sel-alcance']]);const apply=()=>{for(const item of pending){if(item.done||!params.get(item[0]))continue;for(const id of item[1]){const el=document.getElementById(id);if(el&&Array.from(el.options).some(o=>o.value===params.get(item[0]))){item.done=true;el.value=params.get(item[0]);el.dispatchEvent(new Event('change',{bubbles:true}));break;}}}};apply();const observer=new MutationObserver(apply);observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),20000);}
 }
 window.LMBC={url,escape:H,read,write,directory};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
